# Generated by Django 4.2.2 on 2023-06-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('current_class', models.CharField(max_length=4)),
                ('parent_name', models.CharField(max_length=256)),
                ('parent_phone_number', models.CharField(max_length=14)),
                ('genotype', models.CharField(max_length=2)),
                ('blood_group', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('teacher_id', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=6)),
                ('date_of_birth', models.DateField()),
                ('started_work', models.DateField()),
                ('subject', models.CharField(max_length=256)),
                ('class_taught', models.CharField(blank=True, max_length=4)),
                ('emergency_contact', models.CharField(max_length=256)),
                ('emergency_contact_number', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
    ]
