# Generated by Django 4.2.2 on 2023-06-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_address_teacher_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'teachers'},
        ),
    ]
