# Generated by Django 4.2.2 on 2023-06-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_teacher_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('payment_for', models.CharField(max_length=256)),
                ('payment_by', models.CharField(max_length=256)),
                ('received_by', models.CharField(max_length=256)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'verbose_name_plural': 'payments',
            },
        ),
    ]
