# Generated by Django 4.2.2 on 2023-07-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
