# Generated by Django 4.2.2 on 2023-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_payment_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(default='Transfer', max_length=256),
        ),
    ]
