# Generated by Django 4.2.2 on 2023-07-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_mode_of_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='received_by',
            new_name='confirmed_by',
        ),
    ]
