# Generated by Django 4.2.2 on 2023-06-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=9)),
                ('subject_1', models.CharField(max_length=256)),
                ('score_1', models.PositiveIntegerField()),
                ('subject_2', models.CharField(max_length=256)),
                ('score_2', models.PositiveIntegerField()),
                ('subject_3', models.CharField(max_length=256)),
                ('score_3', models.PositiveIntegerField()),
                ('subject_4', models.CharField(max_length=256)),
                ('score_4', models.PositiveIntegerField()),
                ('subject_5', models.CharField(max_length=256)),
                ('score_5', models.PositiveIntegerField()),
                ('subject_6', models.CharField(max_length=256)),
                ('score_6', models.PositiveIntegerField()),
                ('subject_7', models.CharField(max_length=256)),
                ('score_7', models.PositiveIntegerField()),
                ('subject_8', models.CharField(max_length=256)),
                ('score_8', models.PositiveIntegerField()),
                ('subject_9', models.CharField(max_length=256)),
                ('score_9', models.PositiveIntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'verbose_name_plural': 'reports',
            },
        ),
    ]
